from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('', views.home_one, name='home_one'),
    path('home-two/', views.home_two, name='home_two'),
    path('home-three/', views.home_three, name='home_three'),
    path('home-four/', views.home_four, name='home_four'),
    path('about-us/', views.about_us, name='about_us'),
    path('blog-grid-four-columns/', views.blog_grid_four_columns, name='blog_grid_four_columns'),
    path('blog-grid-three-columns/', views.blog_grid_three_columns, name='blog_grid_three_columns'),
    path('blog-left-sidebar/', views.blog_left_sidebar, name='blog_left_sidebar'),
    path('blog-right-sidebar/', views.blog_right_sidebar, name='blog_right_sidebar'),
    path('blog/', views.blog, name='blog'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('compare/', views.compare, name='compare'),
    path('contact/', views.contact, name='contact'),
    path('index-four/', views.index_four, name='index_four'),
    path('index-three/', views.index_three, name='index_three'),
    path('index-two/', views.index_two, name='index_two'),
    path('login/', views.login, name='login'),
    path('my-account/', views.my_account, name='my_account'),
    path('register/', views.register, name='register'),
    path('shop-four-columns/', views.shop_four_columns, name='shop_four_columns'),
    path('shop-left-sidebar/', views.shop_left_sidebar, name='shop_left_sidebar'),
    path('shop-list-left-sidebar/', views.shop_list_left_sidebar, name='shop_list_left_sidebar'),
    path('shop-list-right-sidebar/', views.shop_list_right_sidebar, name='shop_list_right_sidebar'),
    path('shop-list-sidebar/', views.shop_list_sidebar, name='shop_list_sidebar'),
    path('shop-list/', views.shop_list, name='shop_list'),
    path('shop-right-sidebar/', views.shop_right_sidebar, name='shop_right_sidebar'),
    path('shop-three-columns/', views.shop_three_columns, name='shop_three_columns'),
    path('shop/', views.shop, name='shop'),
    path('single-blog/', views.single_blog, name='single_blog'),
    path('single-left-blog/', views.single_left_blog, name='single_left_blog'),
    path('single-product-external/', views.single_product_external, name='single_product_external'),
    path('single-product-group/', views.single_product_group, name='single_product_group'),
    path('single-product-variable/', views.single_product_variable, name='single_product_variable'),
    path('single-product/', views.single_product, name='single_product'),
    path('single-right-blog/', views.single_right_blog, name='single_right_blog'),
    path('wishlist/', views.wishlist, name='wishlist'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
